name: CI

on:
  push:
    branches: [main, brew, asdf]
  pull_request:
    branches: [main]
  schedule:
    - cron: '10 1/2 * * *'

jobs:
  asdf:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Brew cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew
        key: ${{ runner.os }}
    - name: Get asdf
      run: brew install asdf
    - name: Setup asdf configration
      run: . /usr/local/opt/asdf/libexec/asdf.sh
    - name: Add asdf Ruby plugin
      run: asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    - name: Install Ruby 2.7.5
      run: asdf install ruby 2.7.5
    - name: Enable Ruby 2.7.5
      run: asdf reshim ruby

    - name: Check pg_config
      run: which pg_config

    - name: Install pg gem 1.3.5
      run: gem install -N pg -v 1.3.5
